using NUnit.Framework;
using RoguelikeCardFramework.Core;
using UnityEngine;

namespace RoguelikeCardFramework.Tests
{
    public sealed class RandomParityTests
    {
        // Reference values generated by executing src/game/random.ts, not the C# port.
        [Test]
        public void MatchesWebReferenceIncludingUtf16Seed()
        {
            var random = new NamespacedRandom("seed");
            foreach (var expected in new[] { .0066930747125297785, .9735070713795722, .7411143973004073, .7062691792380065, .8046124344691634 })
                Assert.AreEqual(expected, random.Next("combat"));
            CollectionAssert.AreEqual(new[] { 4, 6, 5, 7, 1, 3, 2, 0 }, random.Shuffle("deck", new[] { 0, 1, 2, 3, 4, 5, 6, 7 }));
            random = new NamespacedRandom("废土🌵");
            foreach (var expected in new[] { .9024432045407593, .6245888706762344, .7041964575182647, .6973866710904986, .7917447490617633 })
                Assert.AreEqual(expected, random.Next("combat"));
        }
        [Test]
        public void JsonRoundTripPreservesIndependentStreams()
        {
            var original = new NamespacedRandom("seed");
            original.Next("combat");
            var state = original.ExportState();
            var restored = new NamespacedRandom(JsonUtility.FromJson<RandomState>(JsonUtility.ToJson(state)));
            original.Next("map");
            for (var i = 0; i < 100; i++) Assert.AreEqual(original.Next("combat"), restored.Next("combat"));
            Assert.AreEqual(1, state.counters[0].value);
        }
    }
}
